# Generated by Django 4.1.3 on 2022-11-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description2',
            field=models.TextField(default=''),
        ),
    ]
