# Generated by Django 4.1.3 on 2022-11-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description2',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/projects/img'),
        ),
    ]
